[package]
name = "party_profile"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_party = { git = "https://github.com/misonetwork/miso-party.git", rev = "main" }
country_code = { git = "https://github.com/unconfirmedlabs/country_code.git", rev = "main" }
language_code = { git = "https://github.com/unconfirmedlabs/language_code.git", rev = "main" }
