[package]
name = "party_roles"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_party = { git = "https://github.com/misonetwork/miso-party.git", rev = "main" }
