[package]
name = "party_roles"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso_party = { local = "../../miso-party" }
typed_set = { local = "../lib/typed_set" }
